<?php

namespace AppBundle\Repository;

/**
 * Historique_user_quizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_user_quizzRepository extends \Doctrine\ORM\EntityRepository
{
}
