<?php

namespace AppBundle\Repository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithQuestion() {
        return $this->createQueryBuilder("q")
            ->leftJoin("q.question", "c")
            ->addSelect("c")
            ->getQuery()
            ->getResult();
    }
    public function findAllWithOneQuestion($id) {
        return $this->createQueryBuilder("q")
            ->leftJoin("q.question", "c")
            ->where("q.question = $id")
            ->addSelect("c")
            ->getQuery()
            ->getResult();
    }
}
